### ISSUE TITLE
Plugin failed to download quiltflower 1.8.1

### ISSUE THREAD

**Issue by SanderSmee** [Earthcomputer/quiltflower-intellij-plugin#10]
quiltflower plugin  1.0.3
intellij 2022.2

The plugin can't download quiltflower 1.8.1 jar:

```
java.lang.Throwable: Failed to download quiltflower 1.8.1 from https://maven.quiltmc.org/repository/snapshot/org/quiltmc/quiltflower/1.8.1-SNAPSHOT/quiltflower-1.8.1.jar: 404
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:162)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:122)
	at net.earthcomputer.quiltflowerintellij.UtilKt.runOnBackgroundThreadWithProgress(util.kt:20)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState.downloadQuiltflower$lambda-6$lambda-5(QuiltflowerState.kt:122)
```

**Comment by SettingDust** [comment]
```
java.lang.Throwable: Failed to download quiltflower 1.9.0 from https://maven.quiltmc.org/repository/snapshot/org/quiltmc/quiltflower/1.9.0-SNAPSHOT/quiltflower-1.9.0.jar: 404
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState.doQuiltflowerDownload(QuiltflowerState.kt:197)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState.access$doQuiltflowerDownload(QuiltflowerState.kt:28)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:126)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:124)
	at net.earthcomputer.quiltflowerintellij.UtilKt$runOnBackgroundThreadWithProgress$1.run(util.kt:12)

```
