### ISSUE TITLE
Exception `Error while getting the language of /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.22/d6c44cd08d8f3f9bece8101216dbe6553365c6e3/kotlin-stdlib-1.9.22.jar!/kotlin/reflect/reflect.kotlin_builtins`

### ISSUE THREAD

**Issue by jansorg** [Earthcomputer/quiltflower-intellij-plugin#31]
With 2024.3 eap and the latest version of the plugin the first start of the IDE was severely slowed down with many exceptions thrown by the plugin. I had to disable it before I even tested it with a .class file...
For example:

```
1.9.22/d6c44cd08d8f3f9bece8101216dbe6553365c6e3/kotlin-stdlib-1.9.22.jar!/kotlin/reflect/reflect.kotlin_builtins
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.vineflower.ijplugin.VineflowerInvoker$LanguageFeature.getLanguage(VineflowerInvoker.kt:264)
	at org.vineflower.ijplugin.VineflowerInvoker.getLanguage(VineflowerInvoker.kt:76)
	at org.vineflower.ijplugin.VineflowerDecompilerBase.getLanguage(VineflowerDecompilerBase.kt:83)
	at org.vineflower.ijplugin.VineflowerDecompilerBase.accepts(VineflowerDecompilerBase.kt:66)
	at com.intellij.psi.compiled.ClassFileDecompilers.lambda$find$1(ClassFileDecompilers.java:87)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$intellij_platform_extensions(ExtensionProcessingHelper.kt:27)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:66)
	at com.intellij.psi.compiled.ClassFileDecompilers.find(ClassFileDecompilers.java:87)
	at com.intellij.psi.ClassFileViewProviderFactory.createFileViewProvider(ClassFileViewProviderFactory.java:17)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:289)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:215)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:382)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:163)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.getFiles(PsiDirectoryImpl.java:146)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassesHeuristically(PsiPackageImpl.java:239)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesInDumbMode(PsiPackageImpl.java:205)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:171)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:261)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesInDumbMode(JavaPsiFacadeImpl.java:132)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:96)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:85)
	at org.vineflower.ijplugin.VineflowerInvoker.findClass$lambda$20(VineflowerInvoker.kt:214)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.kt:355)
	at org.vineflower.ijplugin.VineflowerInvoker.findClass(VineflowerInvoker.kt:212)
	at org.vineflower.ijplugin.VineflowerInvoker.doGetClassBytes(VineflowerInvoker.kt:199)
	at org.vineflower.ijplugin.VineflowerInvoker.access$doGetClassBytes(VineflowerInvoker.kt:26)
	at org.vineflower.ijplugin.VineflowerInvoker$getClassBytes$1.invoke(VineflowerInvoker.kt:193)
	at org.vineflower.ijplugin.VineflowerInvoker$getClassBytes$1.invoke(VineflowerInvoker.kt:192)
	at org.vineflower.ijplugin.VineflowerInvoker$decompile$2$1$1.invoke(VineflowerInvoker.kt:144)
	at org.vineflower.ijplugin.VineflowerInvoker$decompile$2$1$1.invoke(VineflowerInvoker.kt:141)
	at org.vineflower.ijplugin.VineflowerInvoker.decompile(VineflowerInvoker.kt:168)
	at org.vineflower.ijplugin.VineflowerDecompilerBase$Companion.getText(VineflowerDecompilerBase.kt:39)
	at org.vineflower.ijplugin.VineflowerDecompilerKotlin$StubBuilder.buildFileStub(VineflowerDecompilerKotlin.kt:49)
	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.lambda$buildStubTree$3(ClassFileStubBuilder.java:58)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.computeWithPreloadedContentHint(VirtualFileImpl.java:88)
	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:55)
	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:19)
	at com.intellij.psi.stubs.BinaryFileStubBuilder$CompositeBinaryFileStubBuilder.buildStubTree(BinaryFileStubBuilder.java:42)
	at com.intellij.psi.stubs.StubTreeBuilder.lambda$buildStubTree$0(StubTreeBuilder.java:121)
	at com.intellij.psi.stubs.StubTreeBuilder.handleStubBuilderException(StubTreeBuilder.java:98)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:121)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:208)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:186)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:155)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:382)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:373)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:298)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:62)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:21)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:287)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:64)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:29)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1641)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$21(FileBasedIndexImpl.java:1512)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$14(FileTypeManagerImpl.java:752)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:822)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:748)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1465)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1440)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$Indexer.getApplierForFileIndexUpdate$lambda$1(IndexUpdateRunner.kt:350)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$3(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.struct.consts.PrimitiveConstant.getString()" because the return value of "org.jetbrains.java.decompiler.struct.consts.ConstantPool.getPrimitiveConstant(int)" is null
	at org.jetbrains.java.decompiler.struct.StructClass.create(StructClass.java:63)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 83 more

```

**Comment by metabrixkt** [comment]
Can confirm in Vineflower plugin 1.2.0 and IntelliJ IDEA 2024.3 (Community Edition) build #IC-243.21565.193
